# Generated by Django 3.1.1 on 2020-09-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=15)),
                ('delivery_address', models.CharField(max_length=256)),
            ],
        ),
    ]
