# Generated by Django 3.1.1 on 2020-09-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20200912_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsets',
            old_name='code',
            new_name='title',
        ),
    ]
